apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clamav
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.wiremind.io
    chart: clamav
    targetRevision: 1.3.2
    helm:
      valueFiles:
        - ../../helm-values/clamav/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: clamav
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
